### ISSUE TITLE
Input IRC uses 100% CPU

### ISSUE THREAD

**Issue by makefu** [logstash-plugins/logstash-input-irc#21]
For some reason the logstash irc input plugin runs at 100% cpu load even though nothing happens.

- Version: 5.4.0
- Operating System: nixos linux
- Config File:
```
input {
  irc {
  channels => [ "#krebs" ]
  host => "irc.freenode.net"
  nick => "testblotter"
  }
}

filter {
}

output {
  stdout { codec => rubydebug }
}
```
- Sample Data: no test data required, java runs at 100% at startup and never drops lower
- Steps to Reproduce:
```
bin/logstash -w 1 --log.level warn -f <my-logstash.conf>
```

**Comment by untergeek** [comment]
I can confirm this behavior, as it's the reason I stopped using this plugin.  It's most likely the underlying ruby gem [Cinch](https://github.com/logstash-plugins/logstash-input-irc/blob/v3.0.2/lib/logstash/inputs/irc.rb#L67), over which we have no control.  I haven't taken the time to investigate alternatives, or to troubleshoot this in any other way.

**Comment by yaauie** [comment]
🤔 This code looks like it could be problematic; whenever the queue is empty, we _immediately_ try again, with no backoff:

> ~~~ ruby
>     while !stop?
>       begin
>         msg = @irc_queue.pop(true)
>         handle_response(msg, output_queue)
>       rescue ThreadError
>         # Empty queue
>       end
>     end
> ~~~
> -- https://github.com/logstash-plugins/logstash-input-irc/blob/v3.0.2/lib/logstash/inputs/irc.rb#L112-L119

**Comment by makefu** [comment]
thanks!
